# Generated by Django 3.1.7 on 2021-04-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_company', models.CharField(max_length=20)),
                ('current_company', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('job_post', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ALU', 'Alumni'), ('STU', 'Student'), ('FAC', 'Faculty')], max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('course_start_year', models.IntegerField(blank=True)),
                ('course_end_year', models.IntegerField(blank=True)),
                ('cell', models.CharField(choices=[('A', 'Alumni Cell'), ('P', 'Placement Cell'), ('C', 'CSFG Cell'), ('N', 'None')], max_length=1)),
                ('achievements', models.CharField(max_length=100)),
                ('highest_degree', models.CharField(max_length=10)),
                ('marital_status', models.CharField(choices=[('M', 'Married'), ('S', 'Single')], max_length=1)),
                ('alumni_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.alumniform')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPostForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('S', 'Student'), ('A', 'Administrator'), ('BM', 'Batch Manager'), ('CM', 'Course Manager'), ('F', 'Faculty')], max_length=2)),
                ('batch_managing', models.IntegerField(blank=True)),
                ('course_managing', models.CharField(blank=True, max_length=20)),
                ('profile', models.ManyToManyField(to='main.ProfileForm')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profileform')),
            ],
        ),
    ]
