# Generated by Django 3.1.3 on 2021-06-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_model',
            name='cell',
            field=models.CharField(blank=True, choices=[('ALUMNI', 'Alumni Cell'), ('PLACEMENT', 'Placement Cell'), ('CSFG', 'CSFG Cell'), ('None', 'None')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='temp_model',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='temp_model',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='temp_model',
            name='role',
            field=models.CharField(blank=True, choices=[('Alumni', 'Alumni'), ('Student', 'Student'), ('Faculty', 'Faculty')], max_length=30, null=True),
        ),
    ]
