# Generated by Django 3.1.3 on 2021-06-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210615_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialpostform',
            name='batch_managing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialpostform',
            name='course_managing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
